# Generated by Django 3.2.3 on 2021-05-31 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='toe',
            name='move',
            field=models.CharField(default=None, max_length=1),
        ),
        migrations.AlterField(
            model_name='toe',
            name='square',
            field=models.CharField(default='', max_length=1),
        ),
    ]
