# Generated by Django 3.2.3 on 2021-06-01 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toe', '0002_auto_20210531_1121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='toe',
            name='move',
        ),
        migrations.AddField(
            model_name='toe',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
